# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82075256ed292838ce858599996cc3926405aa74450ee814a01402f371a79f3a17c6756521cf552b6e7864d84f86a08cc89256a052ff4ce3d77aab492d54bf7c

test:
  secret_key_base: ab8a85ca946040e5e8c051436e5ec72763522d0758ac779b6db255cf7fcd2af827cbc6eaac85f388a38f09ab7490de5259db88437e312dc7d5130989591a2dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
